#nd Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Wispeed' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Wispeed
  
  pod 'AFNetworking', '~> 3.0.4'
  pod 'FMDB'
  pod 'MJExtension'
  pod 'NerdyUI'
  pod 'UMengUShare/UI'
  pod 'UMengUShare/Social/Sina'
  pod 'UMengUShare/Social/WeChat'
  pod 'SMSSDK','~> 2.0.4'
  pod 'MOBFoundation_IDFA'

  target 'WispeedTests' do
    inherit! :search_paths
  end

  target 'WispeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
